[package]
name = "os_dev_specs"
version = "0.1.0"
authors = ["hikalium <hikalium@hikalium.com>"]
edition = "2018"

[dependencies]
notify = "4.0.17"
regex = "1"
clap = { version = "3.1.18", features = ["derive"] }

