[package]
name = "os_dev_specs"
version = "0.1.0"
authors = ["hikalium <hikalium@hikalium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
